import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../assets/images/index";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Inicio",
    link: "/",
  },
  {
    _id: 1002,
    title: "Tienda",
    link: "/tienda",
  },
  {
    _id: 1003,
    title: "Nosotros",
    link: "/nosotros",
  },
  {
    _id: 1004,
    title: "Contacto",
    link: "/contacto",
  },
];
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "Perfume Invictus Paco Rabanne",
    price: "189.00",
    color: "Dorado",
    badge: true,
    des: "Fragancia masculina iconica con notas de pomelo, madera de guayaco y ambar gris. Ideal para el hombre moderno y audaz.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "iPhone 15 Pro Max 256GB",
    price: "5999.00",
    color: "Titanio Natural",
    badge: true,
    des: "El iPhone mas potente con chip A17 Pro, camara de 48MP, pantalla Super Retina XDR de 6.7 pulgadas y cuerpo de titanio.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "AirPods Pro 2da Generacion",
    price: "899.00",
    color: "Blanco",
    badge: true,
    des: "Cancelacion activa de ruido adaptativa, audio espacial personalizado y hasta 6 horas de reproduccion. Estuche con carga USB-C.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Perfume Sauvage Dior EDT",
    price: "320.00",
    color: "Azul",
    badge: true,
    des: "Fragancia masculina fresca y salvaje con notas de bergamota de Calabria y ambroxan. Un clasico contemporaneo de Dior.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "Perfume Invictus Paco Rabanne",
    price: "189.00",
    color: "Dorado",
    badge: true,
    des: "Fragancia masculina iconica con notas de pomelo, madera de guayaco y ambar gris. Ideal para el hombre moderno y audaz.",
  },
  {
    _id: 1002,
    img: spfTwo,
    productName: "iPhone 15 128GB",
    price: "4299.00",
    color: "Negro",
    badge: true,
    des: "Chip A16 Bionic, pantalla Super Retina XDR de 6.1 pulgadas, Dynamic Island y camara dual de 48MP. Diseno en aluminio y vidrio.",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "AirPods Pro 2da Generacion",
    price: "899.00",
    color: "Blanco",
    badge: true,
    des: "Cancelacion activa de ruido adaptativa, audio espacial personalizado y hasta 6 horas de reproduccion. Estuche con carga USB-C.",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "Perfume Sauvage Dior EDT",
    price: "320.00",
    color: "Azul",
    badge: true,
    des: "Fragancia masculina fresca y salvaje con notas de bergamota de Calabria y ambroxan. Un clasico contemporaneo de Dior.",
  },
  {
    _id: 1005,
    img: bestSellerOne,
    productName: "Crema Hidratante Facial Premium",
    price: "85.00",
    color: "Blanco",
    badge: true,
    des: "Crema hidratante con acido hialuronico y vitamina E. Hidratacion profunda de 24 horas para todo tipo de piel.",
  },
  {
    _id: 1006,
    img: bestSellerTwo,
    productName: "Funda Silicona iPhone 15",
    price: "79.00",
    color: "Negro",
    badge: false,
    des: "Funda oficial de silicona con interior de microfibra suave. Proteccion premium contra caidas y rayones.",
  },
  {
    _id: 1007,
    img: bestSellerThree,
    productName: "Cargador MagSafe Apple",
    price: "199.00",
    color: "Blanco",
    badge: true,
    des: "Cargador inalambrico magnetico compatible con iPhone 12 en adelante. Carga rapida de 15W con alineacion perfecta.",
  },
  {
    _id: 1008,
    img: bestSellerFour,
    productName: "Perfume 212 VIP Carolina Herrera",
    price: "275.00",
    color: "Dorado",
    badge: false,
    des: "Fragancia sofisticada con notas de maracuya, ron y almizcle. Para el hombre que vive la noche con estilo.",
  },
  {
    _id: 1009,
    img: newArrOne,
    productName: "Apple Watch Series 9 GPS",
    price: "1899.00",
    color: "Negro",
    badge: true,
    des: "Chip S9, pantalla Retina siempre activa, sensor de oxigeno en sangre y ECG. Resistente al agua hasta 50 metros.",
  },
  {
    _id: 1010,
    img: newArrTwo,
    productName: "Samsung Galaxy S24 Ultra",
    price: "5199.00",
    color: "Negro",
    badge: true,
    des: "Pantalla Dynamic AMOLED 2X de 6.8 pulgadas, camara de 200MP, S Pen integrado y procesador Snapdragon 8 Gen 3.",
  },
  {
    _id: 1011,
    img: newArrThree,
    productName: "Set de Cuidado Facial Completo",
    price: "120.00",
    color: "Variado",
    badge: true,
    des: "Kit completo con limpiador facial, tonico, serum de vitamina C y crema hidratante. Rutina de cuidado para piel radiante.",
  },
  {
    _id: 1012,
    img: newArrFour,
    productName: "iPhone 15 Pro Max 256GB",
    price: "5999.00",
    color: "Titanio Natural",
    badge: false,
    des: "El iPhone mas potente con chip A17 Pro, camara de 48MP, pantalla Super Retina XDR de 6.7 pulgadas y cuerpo de titanio.",
  },
  {
    _id: 1013,
    img: spfOne,
    productName: "Perfume Good Girl Carolina Herrera",
    price: "350.00",
    color: "Negro",
    badge: true,
    des: "Fragancia femenina en su iconico frasco de tacon. Notas de jazmin, cacao y tonka. Irresistiblemente sensual.",
  },
  {
    _id: 1014,
    img: newArrTwo,
    productName: "Samsung Galaxy A55 5G",
    price: "1599.00",
    color: "Azul",
    badge: true,
    des: "Pantalla Super AMOLED de 6.6 pulgadas, triple camara de 50MP, bateria de 5000mAh y conectividad 5G.",
  },
  {
    _id: 1015,
    img: spfFour,
    productName: "Perfume Versace Eros EDT",
    price: "265.00",
    color: "Turquesa",
    badge: false,
    des: "Fragancia masculina con notas de menta, manzana verde y vainilla. Poderosa y seductora como el dios griego del amor.",
  },
  {
    _id: 1016,
    img: bestSellerThree,
    productName: "Cable USB-C Lightning Apple",
    price: "89.00",
    color: "Blanco",
    badge: true,
    des: "Cable original Apple de 1 metro. Carga rapida y sincronizacion de datos. Compatible con todos los dispositivos Apple.",
  },
  {
    _id: 1017,
    img: bestSellerFour,
    productName: "Perfume La Vie Est Belle Lancome",
    price: "390.00",
    color: "Rosa",
    badge: false,
    des: "Fragancia femenina dulce con notas de iris, praline y vainilla. Un himno a la felicidad y la libertad.",
  },
  {
    _id: 1018,
    img: newArrOne,
    productName: "Apple Watch SE 2da Gen",
    price: "1199.00",
    color: "Medianoche",
    badge: true,
    des: "Chip S8, deteccion de choques, seguimiento del sueno y mas de 100 modos de entrenamiento. El Apple Watch esencial.",
  },
  {
    _id: 1019,
    img: newArrTwo,
    productName: "Xiaomi Redmi Note 13 Pro",
    price: "1299.00",
    color: "Negro",
    badge: true,
    des: "Pantalla AMOLED de 6.67 pulgadas 120Hz, camara de 200MP, carga rapida de 67W y bateria de 5100mAh.",
  },
  {
    _id: 1020,
    img: newArrThree,
    productName: "Serum Vitamina C Facial",
    price: "65.00",
    color: "Naranja",
    badge: true,
    des: "Serum concentrado con vitamina C al 20%, acido hialuronico y vitamina E. Ilumina, hidrata y protege la piel.",
  },
  {
    _id: 1021,
    img: spfThree,
    productName: "Audifonos Samsung Galaxy Buds FE",
    price: "349.00",
    color: "Negro",
    badge: true,
    des: "Cancelacion activa de ruido, sonido AKG, bateria de hasta 30 horas con estuche y resistencia al agua IPX2.",
  },
  {
    _id: 1022,
    img: spfFour,
    productName: "Perfume Bleu de Chanel EDT",
    price: "420.00",
    color: "Azul",
    badge: true,
    des: "Fragancia masculina elegante con notas de cedro, sandalo e incienso. Sofisticacion y frescura en cada aplicacion.",
  },
  {
    _id: 1023,
    img: bestSellerOne,
    productName: "Protector Solar Facial SPF 50",
    price: "55.00",
    color: "Blanco",
    badge: true,
    des: "Proteccion solar de amplio espectro con textura ligera y acabado mate. No deja residuo blanco. Uso diario.",
  },
  {
    _id: 1024,
    img: spfOne,
    productName: "Perfume 1 Million Paco Rabanne",
    price: "210.00",
    color: "Dorado",
    badge: true,
    des: "Fragancia masculina audaz con notas de mandarina, canela y cuero. El perfume del hombre que lo tiene todo.",
  },
  {
    _id: 1025,
    img: spfTwo,
    productName: "iPhone 14 128GB",
    price: "3499.00",
    color: "Azul",
    badge: true,
    des: "Chip A15 Bionic, pantalla Super Retina XDR de 6.1 pulgadas, sistema de doble camara avanzado y modo Accion.",
  },
  {
    _id: 1026,
    img: spfThree,
    productName: "Cargador Rapido Samsung 25W",
    price: "69.00",
    color: "Negro",
    badge: true,
    des: "Cargador de pared Super Fast Charging de 25W con cable USB-C incluido. Compatible con Galaxy S24 y Note series.",
  },
  {
    _id: 1027,
    img: bestSellerTwo,
    productName: "Case Transparente iPhone 15 Pro",
    price: "49.00",
    color: "Transparente",
    badge: true,
    des: "Funda transparente con proteccion contra caidas de hasta 2 metros. Muestra el diseno original de tu iPhone.",
  },
  {
    _id: 1028,
    img: bestSellerOne,
    productName: "Mascarilla Facial Hidratante",
    price: "35.00",
    color: "Blanco",
    badge: true,
    des: "Pack de 10 mascarillas faciales con acido hialuronico y aloe vera. Hidratacion intensa en solo 15 minutos.",
  },
  {
    _id: 1029,
    img: bestSellerTwo,
    productName: "Vidrio Templado iPhone 15",
    price: "29.00",
    color: "Transparente",
    badge: false,
    des: "Protector de pantalla 9H de dureza con instalacion facil. Cobertura completa con bordes curvados y anti-huellas.",
  },
  {
    _id: 1030,
    img: bestSellerThree,
    productName: "Power Bank 20000mAh",
    price: "119.00",
    color: "Negro",
    badge: true,
    des: "Bateria externa de alta capacidad con carga rapida USB-C y doble puerto USB-A. Carga tu telefono hasta 5 veces.",
  },
  {
    _id: 1031,
    img: bestSellerFour,
    productName: "Perfume Scandal Jean Paul Gaultier",
    price: "310.00",
    color: "Dorado",
    badge: false,
    des: "Fragancia femenina atrevida con notas de miel, gardenia y caramelo. En su iconico frasco con piernas.",
  },
  {
    _id: 1032,
    img: newArrOne,
    productName: "Samsung Galaxy Watch 6",
    price: "1499.00",
    color: "Negro",
    badge: true,
    des: "Pantalla Super AMOLED, sensor BioActive mejorado, seguimiento del sueno avanzado y Google Wear OS.",
  },
  {
    _id: 1033,
    img: newArrTwo,
    productName: "Samsung Galaxy S24 Plus",
    price: "4499.00",
    color: "Violeta",
    badge: true,
    des: "Pantalla Dynamic AMOLED 2X de 6.7 pulgadas, Galaxy AI integrada, camara de 50MP y bateria de 4900mAh.",
  },
  {
    _id: 1034,
    img: newArrThree,
    productName: "Agua Micelar Limpiadora",
    price: "42.00",
    color: "Rosa",
    badge: true,
    des: "Agua micelar suave para desmaquillar rostro, ojos y labios. Formula sin alcohol ni parabenos. Para todo tipo de piel.",
  },
  {
    _id: 1035,
    img: newArrFour,
    productName: "iPhone 15 Pro 128GB",
    price: "5299.00",
    color: "Titanio Azul",
    badge: false,
    des: "Chip A17 Pro, cuerpo de titanio, boton de Accion, camara de 48MP con zoom optico 3x y USB-C con USB 3.",
  },
  {
    _id: 1036,
    img: spfOne,
    productName: "Perfume Light Blue Dolce & Gabbana",
    price: "245.00",
    color: "Celeste",
    badge: false,
    des: "Fragancia femenina fresca con notas de manzana verde Granny Smith, cedro y ambar. Frescura mediterranea.",
  },
  {
    _id: 1037,
    img: spfFour,
    productName: "Perfume Acqua di Gio Armani",
    price: "299.00",
    color: "Azul Claro",
    badge: false,
    des: "Fragancia masculina acuatica con notas de bergamota, neroil y madera de cedro. Frescura marina atemporal.",
  },
  {
    _id: 1038,
    img: newArrTwo,
    productName: "Xiaomi 14 5G",
    price: "3299.00",
    color: "Negro",
    badge: true,
    des: "Procesador Snapdragon 8 Gen 3, camara Leica de 50MP, pantalla LTPO AMOLED de 6.36 pulgadas y carga rapida 90W.",
  },
  {
    _id: 1039,
    img: bestSellerFour,
    productName: "Perfume Hugo Boss Bottled",
    price: "195.00",
    color: "Ambar",
    badge: false,
    des: "Fragancia masculina clasica con notas de manzana, canela y sandalo. El perfume del hombre con confianza.",
  },
  {
    _id: 1040,
    img: newArrOne,
    productName: "Reloj Casio G-Shock Digital",
    price: "450.00",
    color: "Negro",
    badge: true,
    des: "Reloj resistente a golpes y agua 200m. Cronometro, temporizador, alarma y luz LED. Bateria de larga duracion.",
  },
  {
    _id: 1041,
    img: bestSellerThree,
    productName: "Adaptador USB-C Hub 7 en 1",
    price: "159.00",
    color: "Gris",
    badge: true,
    des: "Hub multipuerto con HDMI 4K, 2x USB 3.0, lector SD/MicroSD, USB-C PD y puerto ethernet. Ideal para laptop.",
  },
  {
    _id: 1042,
    img: newArrThree,
    productName: "Contorno de Ojos Anti-edad",
    price: "75.00",
    color: "Blanco",
    badge: true,
    des: "Crema para contorno de ojos con retinol y peptidos. Reduce ojeras, bolsas y lineas de expresion visiblemente.",
  },
  {
    _id: 1043,
    img: spfThree,
    productName: "Audifonos JBL Tune 520BT",
    price: "179.00",
    color: "Azul",
    badge: true,
    des: "Audifonos inalambricos Bluetooth 5.3 con sonido JBL Pure Bass. Hasta 57 horas de bateria y plegables.",
  },
  {
    _id: 1044,
    img: spfFour,
    productName: "Perfume Ombre Nomade Louis Vuitton",
    price: "1850.00",
    color: "Marron",
    badge: true,
    des: "Fragancia unisex premium de Louis Vuitton con notas de oud, incienso y rosa de Bulgaria. Lujo en su maxima expresion.",
  },
  {
    _id: 1045,
    img: bestSellerOne,
    productName: "Bloqueador Solar Corporal SPF 50",
    price: "45.00",
    color: "Blanco",
    badge: true,
    des: "Protector solar corporal de amplio espectro, resistente al agua por 80 minutos. Textura ligera no grasa.",
  },
  {
    _id: 1046,
    img: spfTwo,
    productName: "Samsung Galaxy Z Flip 5",
    price: "4999.00",
    color: "Lavanda",
    badge: true,
    des: "Smartphone plegable con pantalla FlexWindow de 3.4 pulgadas, camara de 12MP y pantalla interna de 6.7 pulgadas.",
  },
];
// =================== PaginationItems End here =================
